Changes to the file build.gradle and application.properties
klikuskodilla/project_jdp_1904_01 pull request #1
Opened 2019-05-01 20:07 UTC by pszczepcio

2019-05-03 15:28 UTC, klikuskodilla commented
Zwróć uwagę że CircleCI rzuca błędem podczas uruchamiania testów jednostkowych:
2019-05-01 19:58:31.688 ERROR 439 --- [       Thread-6] o.h.engine.jdbc.spi.SqlExceptionHelper   : Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-197]

2019-05-03 15:29 UTC, klikuskodilla requested changes
Zwróć uwagę że CircleCI rzuca błędem podczas uruchamiania testów jednostkowych:
2019-05-01 19:58:31.688 ERROR 439 --- [ Thread-6] o.h.engine.jdbc.spi.SqlExceptionHelper : Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-197]

2019-05-03 19:31 UTC, pszczepcio commented
W którym miejscu jest jest ten błąd CircleCI. Nie mogę tego namierzyć i teraz nie wiem jak sprawdzić czy dalej będę miał ten błąd czy nie

2019-05-04 17:04 UTC, klikuskodilla commented
Możesz spradzić rezultat builda konkretnego commita klikając jak na obrazku
![image](https://user-images.githubusercontent.com/33075397/57182439-59629880-6e9f-11e9-836d-3f7c965225b0.png)

Najnowszy rezultat builda będzie się wyświetlał w tym miejscu
![image](https://user-images.githubusercontent.com/33075397/57182449-7b5c1b00-6e9f-11e9-950a-ddf72b8a5578.png)

2019-05-04 17:05 UTC, klikuskodilla approved these changes

2019-05-04 17:06 UTC, merged