Entity Product
klikuskodilla/project_jdp_1904_01 pull request #24
Opened 2019-05-08 20:27 UTC by KucharM

2019-05-08 21:41 UTC, pszczepcio approved these changes

2019-05-09 12:17 UTC, klikuskodilla requested changes

2019-05-09 12:17 UTC, klikuskodilla commented on src/main/java/com/kodilla/ecommercee/domain/Product.java
> +@Table(name = "Products")
Nazwę tabeli zmień na liczbę pojedyncza czyli Product

2019-05-09 14:56 UTC, MichalOrlowski commented on src/main/java/com/kodilla/ecommercee/domain/Product.java
> +//    @ManyToOne
Przyjęta praktyka - zakomentuj, dlaczego zakomentowałeś lub usuń :)

2019-05-09 16:58 UTC, KucharM commented on src/main/java/com/kodilla/ecommercee/domain/Product.java
> +//    @ManyToOne
rozumiem, na przyszłość wezmę pod uwagę ;), komentowaliśmy relacje do encji które nie były jeszcze zakończone, żeby nie powodować błędy przy kompilacji

2019-05-09 18:40 UTC, klikuskodilla approved these changes

2019-05-09 18:40 UTC, merged