Jdp190401 20 fixed 2
klikuskodilla/project_jdp_1904_01 pull request #49
Opened 2019-05-14 23:16 UTC by pszczepcio

2019-05-15 06:43 UTC, KucharM submitted a review, later dismissed

2019-05-15 06:43 UTC, KucharM commented on src/test/java/com/kodilla/ecommercee/UserTestSuite.java
> +
w każdym assercie powtarza się:
userDao.findById(userId).get()
można by to do jakiejś zmiennej przypisać

2019-05-15 06:43 UTC, KucharM commented on src/test/java/com/kodilla/ecommercee/UserTestSuite.java
> +
aha widzę że to już jest zmienione w innym commicie

2019-05-16 16:01 UTC, klikuskodilla requested changes

2019-05-16 16:01 UTC, klikuskodilla commented on src/test/java/com/kodilla/ecommercee/UserTestSuite.java
> +        System.out.println();
Po co ten System.out

2019-05-17 12:04 UTC, KucharM approved these changes

2019-05-18 17:33 UTC, klikuskodilla approved these changes

2019-05-18 17:33 UTC, merged