Jdp190401 40 naprawa problemu z bazami danych
klikuskodilla/project_jdp_1904_01 pull request #52
Opened 2019-05-16 20:27 UTC by pszczepcio

- usuniecie @Transactional z Dao
- zamiana Eager na Lazy w relacji 1:N
- dodanie @Transactional do ProductTestSuite

2019-05-17 05:56 UTC, KucharM reviewed
mam pytanie co powoduje że usuwamy @Transactional z repozytorium a dodajemy nad testy?

2019-05-17 07:10 UTC, KucharM commented
czy w przypadku późniejszych implementacji metod w repozytorium @Transactional nie trzeba będzie przywrócić?

2019-05-17 10:14 UTC, Makedo81 reviewed
Rozumiem ,ze usuwamy @Transactional w Dao a adnotacja ta bedzie  umieszczona w Service.

2019-05-17 10:42 UTC, Makedo81 commented
> 
> 
> mam pytanie co powoduje że usuwamy @transactional z repozytorium a dodajemy nad testy?

Chodzi o to, zeby wycofac albo wprowadzic dane do bazy danych w trakcie wykonywania testow? Jezeli tak, to dlaczego koliduje to z @Transactional umieszczonym w repozytorium?

2019-05-17 11:58 UTC, KucharM commented
> Rozumiem ,ze usuwamy @transactional w Dao a adnotacja ta bedzie umieszczona w Service.

wydaje mi się że @Transactional w ogóle nie powinno być w repozytorium

2019-05-17 18:39 UTC, pszczepcio commented
Nie potrafię odpowiedźieć na Wasze pytanie gdzie dokładnie ma być @Transactional. Najważniejsze, że teraz działa. Może Karol coś nam więcej powie na ten temat.

2019-05-18 17:47 UTC, klikuskodilla commented
Ta anotacja jest opcjonalna, dodaje się ją np gdy wywołujemy kod wieloetapowo, tutaj nie ma takiej potrzeby. W testach prawdopodobnie też jest opcjonalna

2019-05-19 15:35 UTC, Makedo81 reviewed
A co dokladnie ci nie dziala, ze dodajesz Transactional nad testy. Ja nie dodawalam w moich.

2019-05-19 19:16 UTC, pszczepcio commented
Szczerze mówiąc nie sprawdzałem czy program działa jak nie mam w testach @Transactional. Za chwilę sprawdzę i dam odpwiedź na grupowym kanale.

2019-05-19 20:23 UTC, Makedo81 submitted a review, later dismissed
Faktycznie aplikacja sie uruchamia jezeli usuniemy @Transactional i zamiana Eager na Lazy.W przeciwnym wypadku dzialaja tylko testy

2019-05-20 11:43 UTC, klikuskodilla submitted a review, later dismissed

2019-05-20 12:50 UTC, klikuskodilla requested changes
Dlaczego komentujesz kod zamiast usunąć źródło problemu?

2019-05-20 12:52 UTC, pszczepcio commented
Nie wiedziałem czy mogę od razu usuwać czy nie. To zaraz poprawię to jeszcze raz.

2019-05-20 12:55 UTC, klikuskodilla commented
Jeśli to jest poprawka nie związana z tym taskiem, możesz stworzyć nowy PR który to naprawia, i zaznaczyć tutaj że aktualny czeka na zmergowanie tego drugiego, dzięki czemu tutaj nie trzeba dodawać żadnego.

2019-05-20 13:16 UTC, klikuskodilla commented
problem dla innych deweloperów jest taki że niby coś przestało działać, nie do końca wiadomo co wiec zakomentowałeś, teraz odkomentowałeś i tak naprawdę nie wiadomo co nie działało i czy przyczyna została usunięta

2019-05-20 13:18 UTC, pszczepcio commented
To spróbuję rozdzielić to na dwa taski. a może ten task obecny zamknąc i zrobić nowy żeby to było czytelniejsze?

2019-05-20 13:51 UTC, closed without merging