adding CartDaoTestSuite
klikuskodilla/project_jdp_1904_01 pull request #56
Opened 2019-05-19 07:24 UTC by Makedo81

2019-05-19 15:00 UTC, KucharM requested changes

2019-05-19 15:00 UTC, KucharM commented on src/test/java/com/kodilla/ecommercee/CartDaoTestSuite.java
> +
postaraj się utworzyć zmienne i wtedy zrób asercję wartość oczekiwana do zmiennej

2019-05-19 15:00 UTC, KucharM commented on src/test/java/com/kodilla/ecommercee/CartDaoTestSuite.java
> +
trochę nie czytelne asercje, użyj zmiennych

2019-05-19 15:27 UTC, Makedo81 commented on src/test/java/com/kodilla/ecommercee/CartDaoTestSuite.java
> +
Poprawki naniesione

2019-05-19 17:15 UTC, KucharM submitted a review, later dismissed

2019-05-19 21:25 UTC, pszczepcio approved these changes

2019-05-19 21:25 UTC, pszczepcio commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +CartController {
Chyba Ci się enter przez przypadek wcisnął:)

2019-05-19 21:25 UTC, Makedo81 commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +CartController {
poprawione

2019-05-20 11:58 UTC, klikuskodilla approved these changes

2019-05-20 11:58 UTC, merged