ProductGroupTest
klikuskodilla/project_jdp_1904_01 pull request #58
Opened 2019-05-19 14:28 UTC by KucharM

utworzyłem nowy branch do testów ze wględu na błędy w poprzednim PR: https://github.com/klikuskodilla/project_jdp_1904_01/pull/51
i związane z tym konflikty

2019-05-19 15:45 UTC, Makedo81 requested changes

2019-05-19 15:45 UTC, Makedo81 commented on src/test/java/com/kodilla/ecommercee/ProductGroupTestSuite.java
> +public class ProductGroupTestSuite {
Chyba brakuje testu dla metody findAll()

2019-05-19 21:43 UTC, pszczepcio approved these changes
Jak dla mnie jest ok.

2019-05-20 04:59 UTC, Makedo81 approved these changes

2019-05-20 12:09 UTC, merged