Naprawianie bledow
klikuskodilla/project_jdp_1904_01 pull request #61
Opened 2019-05-20 21:17 UTC by pszczepcio

Wyjaśnienie dlaczego tyle zmian w jednym request na czacie.
zmiany:
1. usunięcie Transactional z Dao
2. Zmiana w niektórych relacjach cascadeType. ALL na cascadeType.REFRESH
3. zmiana fetch.Eager na LAzy
4. Dodanie Transactional w Testach

2019-05-20 21:53 UTC, Makedo81 submitted a review, later dismissed

2019-05-21 12:16 UTC, klikuskodilla requested changes

2019-05-21 12:16 UTC, klikuskodilla commented on src/test/java/com/kodilla/ecommercee/CartDaoTestSuite.java
>          cartDao.deleteById(cartId);
napisz test który sprawdzi czy cascade = CascadeType.REFRESH działa tak jak powinien przypadku cart i order.
Zbędne komentarze do usunięcia

2019-05-21 14:24 UTC, pszczepcio commented on src/test/java/com/kodilla/ecommercee/CartDaoTestSuite.java
>          cartDao.deleteById(cartId);
Metody testów dodane do CartDaoTestSuite i OrderDaoTestsuite.

2019-05-21 14:26 UTC, klikuskodilla approved these changes

2019-05-21 14:30 UTC, KucharM approved these changes

2019-05-21 14:31 UTC, merged