Jdp190401 25
klikuskodilla/project_jdp_1904_01 pull request #63
Opened 2019-05-22 20:10 UTC by pszczepcio

2019-05-23 17:39 UTC, Makedo81 commented on src/main/java/com/kodilla/ecommercee/service/UserService.java
> +    private String newPassword(final UpDateAccount upDateAccount, boolean activeKey) throws ParseException {
Nie wiem czy ta metoda jest potrzebna na tym etapie. Moze umiesc SystemOut zwracajacy jakies info na temat poprawnej aktualizacji password w metodzie updatePassword

2019-05-23 18:44 UTC, Makedo81 requested changes

2019-05-23 18:44 UTC, Makedo81 commented on src/main/java/com/kodilla/ecommercee/service/UserService.java
> +    private boolean newStatus(final ChangeStatusByAdmin changeStatusByAdmin) throws ParseException {
ChangeStatusByAdmnin - > modifiedAdminStatus, chociaz nie do konca mi pasuje ta nazwa , moze ktos inny cos zaproponuje :)

2019-05-23 18:56 UTC, Makedo81 requested changes
Kilka poprawek odnosnie czytelnosci kodu

2019-05-23 18:56 UTC, Makedo81 commented on src/main/java/com/kodilla/ecommercee/service/UserService.java
> +        boolean changeStatus = false;
boolean statusIsChanged

2019-05-23 18:56 UTC, Makedo81 commented on src/main/java/com/kodilla/ecommercee/service/UserService.java
> +    private String newPassword(final UpDateAccount upDateAccount, boolean activeKey) throws ParseException {
private String createNewPassword()

2019-05-23 18:56 UTC, Makedo81 commented on src/main/java/com/kodilla/ecommercee/service/UserService.java
> +    private boolean validityKey(UpDateAccount upDateAccount){
private boolean validateKey()

2019-05-23 18:56 UTC, Makedo81 commented on src/main/java/com/kodilla/ecommercee/service/UserService.java
> +        Calendar finshKeyValidity = Calendar.getInstance();
finshKeyValidity - > keyExpiredTime

2019-05-23 18:56 UTC, Makedo81 commented on src/main/java/com/kodilla/ecommercee/service/UserService.java
> +    private boolean checkAccount(AccauntDto accauntDto){
AccountDto ->UserAccountDto

2019-05-23 18:56 UTC, Makedo81 commented on src/main/java/com/kodilla/ecommercee/service/UserService.java
> +    private boolean checkAccount(AccauntDto accauntDto){
private boolean checkAccount() -> boolean verifyUserAccount()

2019-05-23 18:56 UTC, Makedo81 commented on src/main/java/com/kodilla/ecommercee/service/UserService.java
> +            checkAccount = true;
checkAccount -> accountIsVerified

2019-05-23 18:56 UTC, Makedo81 commented on src/main/java/com/kodilla/ecommercee/domain/UpDateAccount.java
> +public class UpDateAccount {
UpDateAccount -> UpdatedAccount

2019-05-23 19:15 UTC, Makedo81 requested changes

2019-05-23 19:15 UTC, Makedo81 commented on src/main/java/com/kodilla/ecommercee/service/UserService.java
> +                activeKey = true;
activeKey -> keyIsActive

2019-05-23 20:28 UTC, pszczepcio commented
Wszystkie uwagi zostały poprawione.

2019-05-24 19:39 UTC, Makedo81 approved these changes
Nie widze jakis konkretnych bledow w kodzie, warunki w metodach sa w porzadku

2019-05-24 19:59 UTC, KucharM approved these changes

2019-05-24 20:00 UTC, merged